name: Syntax

on:
  push:
    branches:
      - 'main'

jobs:
  find_merge_conflicts:
    runs-on: ubuntu-latest
    name: Find merge conflicts
    steps:
      # Checkout the source code so there are some files to look at.
      - uses: actions/checkout@v4
      # Run the actual merge conflict finder
      - name: Merge Conflict finder
        uses: olivernybroe/action-conflict-finder@v4.0
  php_syntax_check:
    runs-on: ubuntu-latest
    name: PHP Syntax
    needs: [find_merge_conflicts]
    steps:
      # Checkout the source code so there are some files to look at.
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ./vendor
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHP Mess detector
        run: composer phpmd

      - name: Check magic numbers
        run: composer phpmnd

      - name: Check PHP Stan
        run: composer phpstan

      - name: Check PHP Code Sniffer
        run: composer phpcs

  laravel_test:
    runs-on: ubuntu-latest
    name: Run Laravel Tests
    needs: [find_merge_conflicts]
    steps:
      # Checkout del código fuente
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ./vendor
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      # Ejecutar los tests de Laravel
      - name: Run Laravel Tests
        run: composer test  # Ajusta este comando según tu configuración
